variable "log_group_name" {}
variable "log_stream_name" {}
variable "alarm_name" {}
variable "comparison_operator" {}
variable "evaluation_periods" {}
variable "metric_name" {}
variable "namespace" {}
variable "period" {}
variable "statistic" {}
variable "threshold" {}
variable "description" {}
variable "asg_name" {}
variable "alarm_name_rds" {}
variable "comparison_operator_rds" {}
variable "evaluation_periods_rds" {}
variable "metric_name_rds" {}
variable "namespace_rds" {}
variable "period_rds" {}
variable "statistic_rds" {}
variable "threshold_rds" {}
variable "description_rds" {}
variable "rds_mysql_id" {}